data:
    image_size: 64
    channels: 3
    training_keep_image_size: False
    testing_keep_image_size: True
    num_workers: 4
    train_data_dir: '/home/hdd2/zhanggangjian/new_data/train/'  # path to directory of train data
    test_data_dir: '/home/hdd2/zhanggangjian/new_data/test/'  # path to directory of test data
    test_save_dir: '/home/hdd2/zhanggangjian/new_data/test/input_result_0608_aug/'
    val_save_dir: 'output/validation_cosine_8/'
    grid_r: 8
    conditional: True
    tensorboard: 'output/logs_cosine/'

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: cosine
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 8
    batch_size: 16
    n_epochs: 300
    n_iters: 2000000
    snapshot_freq: 20  # model save frequency
    validation_freq: 10000  # validation frequency
    resume: 'output/checkpoints_cosine_0608_aug/diffusion_model'  # path to save the model
    seed: 61 # random seed
    amp: False # automatic mixed precision

sampling:
    batch_size: 8
    last_only: True
    sampling_timesteps: 50

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    warmup_epochs: 100
    lr_schedule: "constant"
    amsgrad: False
    eps: 0.00000001
